[package]
name = "atat"
version = "0.10.1-alpha.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "AT Parser for serial based device crates"
readme = "../README.md"
keywords = ["arm", "cortex-m", "AT", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/atat"
edition = "2018"
documentation = "https://docs.rs/atat"

[lib]
name = "atat"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
nb = "^1"
heapless = { version = "^0.5.6", features = ["serde"] }
serde_at = { path = "../serde_at", version = "^0.10.1-alpha.0"}
atat_derive = { path = "../atat_derive", version = "^0.10.1-alpha.0", optional = true }
serde = { version = "^1", default-features = false }
typenum = "^1"

defmt = { version = "^0.2" }

[dependencies.embedded-hal]
git = "https://github.com/rust-embedded/embedded-hal"
commit = "e8354100b19f6068dbcd74d2a646934295406fc3"

[dev-dependencies]
cortex-m = "0.7.1"
cortex-m-rt = "0.6.13"
cortex-m-rtic = "0.5.5"
panic-halt = "0.2.0"
stm32l4xx-hal = { version = "0.6", features = ["stm32l4x5", "rt"] }

[features]
default = ["derive"]
derive = ["atat_derive"]

std = ["serde_at/std"]

defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []
